logging:
  level:
    org:
      example:
        mapper: debug
datasource:
  master:
    url: jdbc:mysql://localhost:3306/mybatis?serverTimezone=GMT
    username: root
    password: root
  slave:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=GMT
    username: root
    password: root
