logging:
  level:
    org:
      example:
        mapper: debug
datasource:
  master:
    url: jdbc:mysql://121.36.19.76:3306/mybatis?serverTimezone=GMT
    username: root
    password: asdf;lkj
  slave:
    url: jdbc:mysql://121.36.19.76:3306/test?serverTimezone=GMT
    username: root
    password: asdf;lkj
