spring:
  datasource:
    url: jdbc:mysql://121.36.19.76:3306/mybatis?serverTimezone=GMT
    username: root
    password: asdf;lkj
#    drive-class-name: com.mysql.cj.jdbc.Deiver
mybatis:
  mapper-locations: classpath:mapper/*.xml
logging:
  level:
    org:
      example:
        mapper: debug

datasource:
  customize:
    url: jdbc:mysql://121.36.19.76:3306/test?serverTimezone=GMT
    username: root
    password: asdf;lkj
